import { CreateConfigurationDto } from './dto/create-configuration.dto';
import { UpdateConfigurationDto } from './dto/update-configuration.dto';
import { PrismaService } from 'src/prisma/prisma.service';
import { ConfigurationEntityInterface } from './entities/configuration.entity';
export declare class ConfigurationService {
    private readonly _prisma;
    constructor(_prisma: PrismaService);
    create(createConfigurationDto: CreateConfigurationDto): import(".prisma/client").Prisma.Prisma__Config_tableClient<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        enabled: boolean;
        description: string | null;
        wheelType: string;
        skin: string;
        skin2: string;
        skin3: string;
        skin4: string;
        skin5: string;
        skin6: string;
        skin7: string;
        skin8: string;
        skinRotationTime: number;
        statisticsQ: number;
        colorOfLights: string;
        lightsIntensity: number;
        semaphoreIntensity: number;
        semaphoreTime: number;
        semaphoreGreen: number;
        semaphoreYellow: number;
        max: number;
        min: number;
        chip: number;
        b36: number;
        b18: number;
        b12: number;
        b9: number;
        b6: number;
        b7: number;
        bCha1: number;
        bCha2: number;
        lang: string;
        lang2: string;
        lang3: string;
        croupierLang: string;
        croupierLang2: string;
        croupierLang3: string;
        userId: number | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, import(".prisma/client").Prisma.PrismaClientOptions>;
    catch(error: any): void;
    findAll: (q: number, config: number, enabledQuery: string) => Promise<ConfigurationEntityInterface[]>;
    findOne: (id: number) => Promise<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        enabled: boolean;
        description: string | null;
        wheelType: string;
        skin: string;
        skin2: string;
        skin3: string;
        skin4: string;
        skin5: string;
        skin6: string;
        skin7: string;
        skin8: string;
        skinRotationTime: number;
        statisticsQ: number;
        colorOfLights: string;
        lightsIntensity: number;
        semaphoreIntensity: number;
        semaphoreTime: number;
        semaphoreGreen: number;
        semaphoreYellow: number;
        max: number;
        min: number;
        chip: number;
        b36: number;
        b18: number;
        b12: number;
        b9: number;
        b6: number;
        b7: number;
        bCha1: number;
        bCha2: number;
        lang: string;
        lang2: string;
        lang3: string;
        croupierLang: string;
        croupierLang2: string;
        croupierLang3: string;
        userId: number | null;
    }>;
    update(id: number, updateConfigurationDto: UpdateConfigurationDto): Promise<{
        id: number;
        createdAt: Date;
        updatedAt: Date;
        enabled: boolean;
        description: string | null;
        wheelType: string;
        skin: string;
        skin2: string;
        skin3: string;
        skin4: string;
        skin5: string;
        skin6: string;
        skin7: string;
        skin8: string;
        skinRotationTime: number;
        statisticsQ: number;
        colorOfLights: string;
        lightsIntensity: number;
        semaphoreIntensity: number;
        semaphoreTime: number;
        semaphoreGreen: number;
        semaphoreYellow: number;
        max: number;
        min: number;
        chip: number;
        b36: number;
        b18: number;
        b12: number;
        b9: number;
        b6: number;
        b7: number;
        bCha1: number;
        bCha2: number;
        lang: string;
        lang2: string;
        lang3: string;
        croupierLang: string;
        croupierLang2: string;
        croupierLang3: string;
        userId: number | null;
    }>;
    remove(id: number): string;
}
