-- Particionado mensual de game_table por workday
-- Convierte game_table en una tabla particionada por rango de fechas (mensual),
-- crea particiones para los meses con datos existentes y funciones de
-- mantenimiento para garantizar que la partición del mes correspondiente
-- exista antes de cada inserción.

-- 1) Renombrar la tabla actual y su secuencia para poder recrearla
ALTER TABLE IF EXISTS public.game_table RENAME TO game_table_old;
ALTER SEQUENCE IF EXISTS public.game_table_id_seq RENAME TO game_table_old_id_seq;

-- 2) Tabla particionada
CREATE TABLE public.game_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    workday DATE NOT NULL,
    game_number INTEGER NOT NULL,
    win_number INTEGER,
    rpm INTEGER,
    open_table BOOLEAN,
    clockwise BOOLEAN NOT NULL,
    enabled BOOLEAN,
    fk_croupier INTEGER REFERENCES public.user_table(id),
    fk_table INTEGER NOT NULL REFERENCES public.table_table(id),
    PRIMARY KEY (workday, id),
    UNIQUE (workday, fk_table, created_at, game_number)
) PARTITION BY RANGE (workday);

-- 3) Particiones para los meses con datos existentes
DO $$
DECLARE
    m DATE;
    start_date DATE;
    end_date DATE;
    part_name TEXT;
BEGIN
    FOR m IN
        SELECT DISTINCT date_trunc('month', COALESCE(workday, created_at::date))::date
        FROM public.game_table_old
    LOOP
        start_date := m;
        end_date := (m + INTERVAL '1 month')::date;
        part_name := 'game_table_' || to_char(m, 'YYYY_MM');
        EXECUTE format('CREATE TABLE public.%I PARTITION OF public.game_table FOR VALUES FROM (%L) TO (%L)', part_name, start_date::text, end_date::text);
    END LOOP;
END $$;

-- 4) Copiar los datos existentes (normalizando workday nulo)
INSERT INTO public.game_table (id, created_at, updated_at, workday, game_number, win_number, rpm, open_table, clockwise, enabled, fk_croupier, fk_table)
SELECT id, created_at, updated_at, COALESCE(workday, created_at::date), game_number, win_number, rpm, open_table, clockwise, enabled, fk_croupier, fk_table
FROM public.game_table_old;

-- 5) Ajustar la secuencia al máximo id copiado
SELECT setval(pg_get_serial_sequence('public.game_table', 'id'), GREATEST((SELECT max(id) FROM public.game_table), 1));

-- 6) Eliminar la tabla anterior
DROP TABLE public.game_table_old;

-- 7) RLS y permisos de la nueva tabla
ALTER TABLE public.game_table ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "insertar_jugadas" ON public.game_table;
DROP POLICY IF EXISTS "insertar_jugadas_anon" ON public.game_table;
DROP POLICY IF EXISTS "leer_jugadas" ON public.game_table;

CREATE POLICY "insertar_jugadas" ON public.game_table
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "insertar_jugadas_anon" ON public.game_table
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "leer_jugadas" ON public.game_table
  FOR SELECT TO anon, authenticated USING (true);

GRANT ALL PRIVILEGES ON public.game_table TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.game_table_id_seq TO anon, authenticated, service_role;

-- 8) Función para garantizar la existencia de una partición mensual
CREATE OR REPLACE FUNCTION public.create_game_table_partition(target_month DATE)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    start_date DATE := date_trunc('month', target_month)::date;
    end_date DATE := (date_trunc('month', target_month) + INTERVAL '1 month')::date;
    part_name TEXT := 'game_table_' || to_char(start_date, 'YYYY_MM');
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public' AND c.relname = part_name
    ) THEN
        EXECUTE format(
            'CREATE TABLE public.%I PARTITION OF public.game_table FOR VALUES FROM (%L) TO (%L)',
            part_name, start_date::text, end_date::text
        );
    END IF;
END;
$$;

GRANT ALL PRIVILEGES ON FUNCTION public.create_game_table_partition(DATE) TO anon, authenticated, service_role;
GRANT ALL PRIVILEGES ON FUNCTION public.create_game_table_partition(DATE) TO postgres;

-- 9) insertar_juegos con partición autogenerada y last_game_registered
CREATE OR REPLACE FUNCTION public.insertar_juegos(j JSONB)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    -- Asegurar la partición del mes de cada juego antes de insertar (idempotente)
    PERFORM public.create_game_table_partition(s.d)
    FROM (
        SELECT DISTINCT COALESCE((elem->>'workday')::DATE, to_timestamp((elem->>'created_at')::BIGINT / 1000)::DATE) AS d
        FROM jsonb_array_elements(j) AS elem
    ) s;

    INSERT INTO public.game_table (
        created_at,
        updated_at,
        workday,
        game_number,
        win_number,
        rpm,
        open_table,
        clockwise,
        enabled,
        fk_croupier,
        fk_table
    )
    SELECT
        to_timestamp((elem->>'created_at')::BIGINT / 1000),
        to_timestamp((elem->>'updated_at')::BIGINT / 1000),
        COALESCE((elem->>'workday')::DATE, to_timestamp((elem->>'created_at')::BIGINT / 1000)::DATE),
        (elem->>'game_number')::INT,
        (elem->>'win_number')::INT,
        (elem->>'rpm')::INT,
        (elem->>'open_table')::BOOLEAN,
        (elem->>'clockwise')::BOOLEAN,
        (elem->>'enabled')::BOOLEAN,
        (elem->>'fk_croupier')::INT,
        (elem->>'fk_table')::INT
    FROM jsonb_array_elements(j) AS elem
    ON CONFLICT (workday, fk_table, created_at, game_number)
    DO UPDATE SET
        updated_at = EXCLUDED.updated_at,
        win_number = EXCLUDED.win_number,
        rpm = EXCLUDED.rpm,
        open_table = EXCLUDED.open_table,
        clockwise = EXCLUDED.clockwise,
        enabled = EXCLUDED.enabled,
        fk_croupier = EXCLUDED.fk_croupier;

    UPDATE public.table_table t
    SET last_game_registered = sub.max_game,
        updated_at = CURRENT_TIMESTAMP
    FROM (
        SELECT (elem->>'fk_table')::INT AS fk_table,
               MAX((elem->>'game_number')::INT) AS max_game
        FROM jsonb_array_elements(j) AS elem
        GROUP BY (elem->>'fk_table')::INT
    ) sub
    WHERE t.id = sub.fk_table
      AND sub.max_game > t.last_game_registered;
END;
$$;

GRANT ALL PRIVILEGES ON FUNCTION public.insertar_juegos(JSONB) TO anon, authenticated, service_role;
